import type { DiscoveryResult, ExportBundle, LeadCard, SearchFilters } from './types';

export const DEFAULT_FILTERS: SearchFilters = {
  search: '',
  region: '',
  minScore: 70,
  stage: '',
  usdBackedOnly: true,
  internationalBackingOnly: false,
};

export const SEED_LEADS: LeadCard[] = [
  {
    id: 'aurora-semi',
    name: 'Aurora Semi Systems',
    normalized_name: 'aurora semi systems',
    website: 'https://aurorasemi.example',
    hq_country: 'Singapore',
    china_link_type: 'founder-origin',
    global_regions: ['Singapore', 'Shenzhen', 'San Jose'],
    summary: 'Designs edge AI accelerator modules for robotics and industrial vision teams expanding outside China.',
    company_profile: 'Singapore-headquartered semiconductor platform with China-origin founders, US reseller relationships, and stated plans to support OEM customers in North America and ASEAN.',
    funding_signal_summary: 'Series B included US strategic investor participation and Singapore institutional backing, indicating comfort with cross-border scaling.',
    globalization_signal_summary: 'Operates bilingual hiring pages, lists Singapore HQ, Shenzhen hardware team, and US channel coverage with overseas customer support hours.',
    infra_demand_likelihood: 'High likelihood of needing burst inference, cross-border API mediation, and export-aware infrastructure for customer demos and partner integrations.',
    target_contact_roles: ['CTO', 'VP Engineering', 'Head of Platform', 'Global IT Director'],
    recommended_opening_angle: 'Position DCDeepTech as the fastest route to compliant Singapore-to-China inference access plus OCP-aligned racks for hardware labs and customer POCs.',
    employee_band: '120-250',
    stage: 'Series B',
    is_usd_backed: true,
    international_backing: true,
    latest_funding_event: {
      id: 'fund-aurora-1',
      company_id: 'aurora-semi',
      announced_at: '2025-09-18',
      round_name: 'Series B',
      amount_usd_m: 42,
      investors: ['North Bridge Capital', 'Temasek-backed deep tech fund', 'US strategic semiconductor investor'],
      funding_signal_summary: 'Series B included US strategic investor participation and Singapore institutional backing, indicating comfort with cross-border scaling.',
    },
    lead_score: {
      company_id: 'aurora-semi',
      funding_score: 90,
      globalization_score: 95,
      infra_fit_score: 88,
      qualification_confidence: 82,
      final_lead_score: 89,
      score_rationale: 'Strong USD-backed growth, explicit cross-border footprint, and a hardware-plus-platform profile that maps well to DCDeepTech offerings.',
      last_qualified_at: '2026-04-12T10:00:00Z',
      target_roles: ['CTO', 'VP Engineering', 'Head of Platform', 'Global IT Director'],
      opening_angle: 'Position DCDeepTech as the fastest route to compliant Singapore-to-China inference access plus OCP-aligned racks for hardware labs and customer POCs.',
    },
  },
  {
    id: 'harbor-robotics',
    name: 'Harbor Robotics Cloud',
    normalized_name: 'harbor robotics cloud',
    website: 'https://harborrobotics.example',
    hq_country: 'Hong Kong',
    china_link_type: 'ops-in-mainland',
    global_regions: ['Hong Kong', 'Shanghai', 'Munich'],
    summary: 'Runs fleet orchestration and simulation infrastructure for warehouse robot operators across Europe and Greater China.',
    company_profile: 'International robotics SaaS firm with operations in mainland China and Europe, selling uptime-critical simulation and model serving workflows to logistics operators.',
    funding_signal_summary: 'Large USD-denominated growth round with European logistics participation supports international expansion and enterprise infrastructure spend.',
    globalization_signal_summary: 'Mentions EU deployments, multilingual support, and integration partnerships with European systems integrators.',
    infra_demand_likelihood: 'Strong need for API gateway controls, global inference endpoints, and policy separation between China operations and overseas customer data.',
    target_contact_roles: ['COO', 'Head of AI Infrastructure', 'Director of Solutions', 'CISO'],
    recommended_opening_angle: 'Lead with resilient gateway + compliance posture for cross-border robot telemetry and model routing, then expand into dedicated inference clusters.',
    employee_band: '250-500',
    stage: 'Series C',
    is_usd_backed: true,
    international_backing: true,
    latest_funding_event: {
      id: 'fund-harbor-1',
      company_id: 'harbor-robotics',
      announced_at: '2025-04-03',
      round_name: 'Series C',
      amount_usd_m: 65,
      investors: ['Atlantic Horizon Ventures', 'European logistics fund', 'Existing Hong Kong family office'],
      funding_signal_summary: 'Large USD-denominated growth round with European logistics participation supports international expansion and enterprise infrastructure spend.',
    },
    lead_score: {
      company_id: 'harbor-robotics',
      funding_score: 90,
      globalization_score: 95,
      infra_fit_score: 90,
      qualification_confidence: 82,
      final_lead_score: 90,
      score_rationale: 'High-growth robotics operator with global deployment complexity and a clear need for routing, compliance, and managed inference.',
      last_qualified_at: '2026-04-12T10:00:00Z',
      target_roles: ['COO', 'Head of AI Infrastructure', 'Director of Solutions', 'CISO'],
      opening_angle: 'Lead with resilient gateway + compliance posture for cross-border robot telemetry and model routing, then expand into dedicated inference clusters.',
    },
  },
  {
    id: 'jade-inference',
    name: 'Jade Inference Labs',
    normalized_name: 'jade inference labs',
    website: 'https://jadeinference.example',
    hq_country: 'United States',
    china_link_type: 'research-team',
    global_regions: ['Palo Alto', 'Beijing', 'Singapore'],
    summary: 'Builds vertical inference tooling for multilingual customer support and developer copilots.',
    company_profile: 'US-incorporated applied AI company with research and annotation presence in Beijing, plus commercial expansion in Singapore for APAC accounts.',
    funding_signal_summary: 'US-led Series A plus Singapore go-to-market angels suggest fast overseas customer acquisition and willingness to buy infrastructure.',
    globalization_signal_summary: 'Highlights US fundraising, APAC go-to-market hiring, and cross-border data handling constraints in customer security docs.',
    infra_demand_likelihood: 'High demand for compliance-aware gatewaying, managed inference, and traffic localization for enterprise accounts that split workloads by region.',
    target_contact_roles: ['CEO', 'Head of Infrastructure', 'VP Product', 'Solutions Architect'],
    recommended_opening_angle: 'Offer DCDeepTech as a launchpad for APAC enterprise expansion with Singapore control plane governance and China-compatible deployment options.',
    employee_band: '80-150',
    stage: 'Series A',
    is_usd_backed: true,
    international_backing: true,
    latest_funding_event: {
      id: 'fund-jade-1',
      company_id: 'jade-inference',
      announced_at: '2025-11-08',
      round_name: 'Series A',
      amount_usd_m: 18.5,
      investors: ['US enterprise AI fund', 'Singapore operator angel syndicate'],
      funding_signal_summary: 'US-led Series A plus Singapore go-to-market angels suggest fast overseas customer acquisition and willingness to buy infrastructure.',
    },
    lead_score: {
      company_id: 'jade-inference',
      funding_score: 90,
      globalization_score: 95,
      infra_fit_score: 96,
      qualification_confidence: 82,
      final_lead_score: 92,
      score_rationale: 'Very strong fit for cross-border inference, governance, and API-layer infrastructure due to regional customer expansion and distributed teams.',
      last_qualified_at: '2026-04-12T10:00:00Z',
      target_roles: ['CEO', 'Head of Infrastructure', 'VP Product', 'Solutions Architect'],
      opening_angle: 'Offer DCDeepTech as a launchpad for APAC enterprise expansion with Singapore control plane governance and China-compatible deployment options.',
    },
  },
  {
    id: 'silkchain-health',
    name: 'SilkChain Health AI',
    normalized_name: 'silkchain health ai',
    website: 'https://silkchainhealth.example',
    hq_country: 'Singapore',
    china_link_type: 'supply-chain',
    global_regions: ['Singapore', 'Suzhou', 'Dubai'],
    summary: 'Develops imaging analysis and hospital workflow tools for clinics serving medical tourists and regional health groups.',
    company_profile: 'Healthcare AI operator serving hospital groups across Southeast Asia and China-linked device partners, with growing regional compliance obligations.',
    funding_signal_summary: 'International healthcare strategic participation raises compliance and regional deployment complexity even without a clear USD-led cap table.',
    globalization_signal_summary: 'Signals regional expansion through distributor programs, Gulf partnerships, and multilingual product releases.',
    infra_demand_likelihood: 'Moderate to high need for secure inference service, auditability, and compliance support where patient data and overseas deployment intersect.',
    target_contact_roles: ['Chief Digital Officer', 'VP Partnerships', 'Head of Compliance', 'CTO'],
    recommended_opening_angle: 'Start from regulated AI infrastructure and audit logging for regional health deployments, then discuss managed inference and gateway controls.',
    employee_band: '150-300',
    stage: 'Series B',
    is_usd_backed: false,
    international_backing: true,
    latest_funding_event: {
      id: 'fund-silk-1',
      company_id: 'silkchain-health',
      announced_at: '2024-12-15',
      round_name: 'Series B',
      amount_usd_m: 27,
      investors: ['Regional healthcare fund', 'Middle East hospital group'],
      funding_signal_summary: 'International healthcare strategic participation raises compliance and regional deployment complexity even without a clear USD-led cap table.',
    },
    lead_score: {
      company_id: 'silkchain-health',
      funding_score: 68,
      globalization_score: 95,
      infra_fit_score: 86,
      qualification_confidence: 82,
      final_lead_score: 82,
      score_rationale: 'Strong compliance-driven infra fit with credible international signals, though the funding profile is less clearly USD-led.',
      last_qualified_at: '2026-04-12T10:00:00Z',
      target_roles: ['Chief Digital Officer', 'VP Partnerships', 'Head of Compliance', 'CTO'],
      opening_angle: 'Start from regulated AI infrastructure and audit logging for regional health deployments, then discuss managed inference and gateway controls.',
    },
  },
];

export const DEFAULT_DISCOVERY_RESULT: DiscoveryResult = {
  query: 'China-linked AI infrastructure buyers',
  candidates_found: 4,
  shortlisted: SEED_LEADS.slice(0, 3),
  connector_notes: [
    'Connector searched funding narratives, overseas office signals, and China-linked operating footprints.',
    'Scoring favors explicit international backing and AI infra complexity over raw company size.',
    'Outbound automation is intentionally excluded in v1; analysts review and export qualified lead cards.',
  ],
};

export const DEFAULT_EXPORT_BUNDLE: ExportBundle = {
  format: 'csv',
  generated_at: '2026-04-12T10:00:00Z',
  record_count: SEED_LEADS.length,
  columns: [
    'company',
    'hq_country',
    'website',
    'stage',
    'final_lead_score',
    'funding_signal_summary',
    'globalization_signal_summary',
    'infra_demand_likelihood',
    'target_contact_roles',
    'recommended_opening_angle',
  ],
  payload: '',
};
