apiVersion: v1
kind: Service
metadata:
  name: sg-gateway
  namespace: platform-sg
spec:
  selector:
    app: sg-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
