#!/usr/bin/env python3
"""
Bootstrap script — generates the first DCDeepTech admin API key.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  WARNING: Run manually ONCE per environment. Do NOT automate.
  Do NOT add to CI/CD pipelines. Do NOT run in loops.
  Each run creates a NEW admin key; old keys are NOT revoked automatically.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Usage (from monorepo root):
    make seed
  OR manually:
    cd platform-sg/services/gateway && python ../../../scripts/seed-admin-key.py

The full key is printed to stdout exactly ONCE.
Store it immediately in a secrets manager, password vault, or .env file.
It cannot be recovered after this script exits.

Security notes:
  - Old keys are not revoked automatically — revoke via POST /admin/api-keys/{id}/revoke
  - Do not pipe this output to a log file without redacting the key line
"""

import sys
from pathlib import Path

# Resolve gateway service root so imports work regardless of CWD
_GATEWAY_ROOT = Path(__file__).parent.parent / "platform-sg" / "services" / "gateway"
sys.path.insert(0, str(_GATEWAY_ROOT))

from keys.service import ApiKeyService
from keys.schemas import CreateKeyRequest, KeyScope

_ADMIN_SCOPES = [
    KeyScope.ADMIN_KEYS,
    KeyScope.ADMIN_TENANTS,
    KeyScope.CHAT_COMPLETIONS,
    KeyScope.INTERNAL_ROUTING,
]


def main() -> None:
    service = ApiKeyService()

    req = CreateKeyRequest(
        tenant_id="dcdt-admin",
        description="Bootstrap admin key — generated by seed_admin_key.py",
        scopes=_ADMIN_SCOPES,
    )

    result = service.create_key(req)

    sep = "=" * 64
    print(f"\n{sep}")
    print("  DCDeepTech Admin API Key — STORE SECURELY")
    print(sep)
    print(f"  Key ID   : {result.key_id}")
    print(f"  Prefix   : {result.key_prefix}")
    print(f"  Tenant   : {result.tenant_id}")
    print(f"  Scopes   : {', '.join(result.scopes)}")
    print(f"  Created  : {result.created_at.isoformat()}")
    print(sep)
    print(f"\n  FULL KEY (shown once):\n\n    {result.key}\n")
    print(sep)
    print("\n  Add to backend/.env:")
    print(f"    ADMIN_BOOTSTRAP_KEY_ID={result.key_id}")
    print(f"\n  Use in Authorization header:")
    print(f"    Authorization: Bearer {result.key}")
    print(f"\n{sep}\n")


if __name__ == "__main__":
    main()
